# Generated by Django 5.0.4 on 2024-04-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orderrequestsummary',
            table='order_request_summary_view',
        ),
    ]
